IF OBJECT_ID('dbo.AUTH_USER', 'P') IS NOT NULL
	DROP PROCEDURE dbo.AUTH_USER
GO

CREATE PROCEDURE dbo.AUTH_USER(
	@USERNAME VARCHAR(30),
	@PASSWD VARCHAR(50),
	@IT_EXISTS INT = 0 OUTPUT
)
AS
BEGIN
	SELECT @IT_EXISTS = COUNT(*) FROM dbo.APP_USER WHERE USERNAME = @USERNAME 
	AND PASSWORD = @PASSWD
END
