IF OBJECT_ID('dbo.AGE_FROM_DOB', 'FN') IS NOT NULL
	DROP FUNCTION dbo.AGE_FROM_DOB
GO

CREATE FUNCTION dbo.AGE_FROM_DOB
(
	@CURR_DATE DATE, 
	@DOB DATE
)RETURNS INT
BEGIN
	DECLARE @CURR_DTIME DATETIME
	DECLARE @DOB_DTIME DATETIME
	DECLARE @AGE INT
	
	SET @CURR_DTIME = @CURR_DATE
	SET @DOB_DTIME = @DOB
	
	SET @AGE = (CONVERT(int,CONVERT(char(8),@CURR_DTIME,112))-CONVERT(char(8),@DOB_DTIME,112))/10000
	RETURN @AGE
END