IF OBJECT_ID('dbo.PERSON', 'U') IS NOT NULL
	DROP TABLE dbo.PERSON
GO

CREATE TABLE dbo.PERSON
(
	ID INT IDENTITY PRIMARY KEY,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	DOB DATE NOT NULL,
	AGE AS dbo.AGE_FROM_DOB(GETDATE(), DOB),
	WEIGHT SMALLINT NULL DEFAULT 0,
	ACTIVE TINYINT NOT NULL DEFAULT 1
)